# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            RConics
tagline:          "a free and open-source package for computations on conics and much more"
description:      'RConics'
url:              https://emanuelhuber.github.io/RConics/
baseurl:          /RConics
logo:             http://emanuelhuber.github.io/RConics/img/RConics_logo.png
#twitter:
#  username: RGPRsoftware
#  card: summary
social:
  name: RConics package
#  links:
#    - https://www.linkedin.com/company/rgpr-open-source-gpr-processing/
#    - https://github.com/open-source-GPR-software-processing
#    - https://www.researchgate.net/project/RGPR-a-free-and-open-source-software-package-for-ground-penetrating-radar-GPR-data-processing
    
    
#author:
#  name:           'Mark Otto'
#  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          0.2

#github:
#  repo:           https://github.com/poole/hyde
analytics:
  provider: "google-universal"
google:
  tracking_id: "G-P2W6DGVKRP"

# jekyll plugins
plugins:
  - jekyll-seo-tag
